---
- hosts: all
  gather_facts: no
  vars_files:
    - vars/main.yml
    - vars/vault

  roles:
    - role: bastion2
      tags: [ never, bastion2 ]
      when: inventory_hostname == "192.168.16.5"

    - role: bastion2-post
      tags: [ never, bastion2 ]
      when: inventory_hostname == "172.16.0.8"